#! /bin/bash
bigchaindbNODE="http://testchain.chon.group:9984"
VELLUSCINUM_CLI="java -jar lib/velluscinum_0.2-beta.jar"

echo "Preparing cryptocurrency to execute the example"
echo "Using $bigchaindbNODE as Node in BigchainDB Network"
echo " "

if [ -f "velluscinum.lock" ] ; then
    rm velluscinum.lock
fi
rm .jacamoCoin/*

echo "Creating the Bank Of Agents and the JacamoCoin"
$VELLUSCINUM_CLI buildWallet .jacamoCoin/bankOfAgents
$VELLUSCINUM_CLI buildAsset  .jacamoCoin/JacamoCoin "cryptocurrency:JacamoCoin" "null:null"
$VELLUSCINUM_CLI deployToken $bigchaindbNODE .jacamoCoin/bankOfAgents.privkey .jacamoCoin/bankOfAgents.publkey .jacamoCoin/JacamoCoin.asset 100000

echo " "
echo "Transfering 50000 JacamoCoin to Giacomo Agent"
$VELLUSCINUM_CLI buildWallet .jacamoCoin/giacomoWallet
JacamoCoinID=`cat .jacamoCoin/JacamoCoin.assetId`
$VELLUSCINUM_CLI transferToken $bigchaindbNODE .jacamoCoin/bankOfAgents.privkey .jacamoCoin/bankOfAgents.publkey $JacamoCoinID .jacamoCoin/giacomoWallet.publkey 10700

echo " "
echo "Updating beliefs about jacamoCoin"
mv src/agt/inc/common.asl src/agt/inc/common.asl.bkp
echo "jacamoCoin(\"$JacamoCoinID\"). /* AutoGenerated - consult startMAS.sh*/" > src/agt/inc/common.asl
echo "bigchaindbNode(\"$bigchaindbNODE\"). /* AutoGenerated - consult startMAS.sh*/" >> src/agt/inc/common.asl
cat src/agt/inc/common.asl.bkp | grep -v "AutoGenerated" >> src/agt/inc/common.asl
rm src/agt/inc/common.asl.bkp

echo " "
echo "Updating beliefs about Giacomo Wallet"
mv src/agt/giacomo.asl src/agt/giacomo.asl.bkp
GiacomoPrivateKey=`cat .jacamoCoin/giacomoWallet.privkey`
GiacomoPublickKey=`cat .jacamoCoin/giacomoWallet.publkey`
echo "myWallet(\"$GiacomoPrivateKey\",\"$GiacomoPublickKey\"). /* Auto generated GiacomoWallet - consult startMAS.sh*/" > src/agt/giacomo.asl
cat src/agt/giacomo.asl.bkp | grep -v "Auto generated GiacomoWallet" >> src/agt/giacomo.asl
rm src/agt/giacomo.asl.bkp

echo " "
echo "Executing the house_building jacamo example"

#Run gradle (see the run task on build.gradle file)
#./gradlew buildJCMDeps
#./gradlew run