#! /bin/bash
bigchaindbNODE="http://testchain.chon.group:9984"
VELLUSCINUM_CLI="java -jar houseBuilding/lib/velluscinum_0.9-rc.jar"

echo "Preparing cryptocurrency to execute the example"
echo "Using $bigchaindbNODE as Node in BigchainDB Network"
echo " "

if [ -f "velluscinum.lock" ] ; then
    rm velluscinum.lock
fi

mkdir -p .jacamoCoin

rm .jacamoCoin/*

echo "Creating the Bank Of Agents and the JacamoCoin"
$VELLUSCINUM_CLI buildWallet .jacamoCoin/bankOfAgents
$VELLUSCINUM_CLI buildAsset  .jacamoCoin/JacamoCoin "cryptocurrency:JacamoCoin" "null:null"
$VELLUSCINUM_CLI deployToken $bigchaindbNODE .jacamoCoin/bankOfAgents.privkey .jacamoCoin/bankOfAgents.publkey .jacamoCoin/JacamoCoin.asset 100000

echo " "
echo "Transfering 50000 JacamoCoin to Giacomo Agent"
$VELLUSCINUM_CLI buildWallet .jacamoCoin/giacomoWallet
JacamoCoinID=`cat .jacamoCoin/JacamoCoin.assetId`
$VELLUSCINUM_CLI transferToken $bigchaindbNODE .jacamoCoin/bankOfAgents.privkey .jacamoCoin/bankOfAgents.publkey $JacamoCoinID .jacamoCoin/giacomoWallet.publkey 10700

echo " "
echo "Updating beliefs about jacamoCoin"
mv houseBuilding/src/agt/inc/common.asl houseBuilding/src/agt/inc/common.asl.bkp
echo "jacamoCoin(\"$JacamoCoinID\"). /* AutoGenerated - consult createCoin.sh*/" > houseBuilding/src/agt/inc/common.asl
echo "bigchaindbNode(\"$bigchaindbNODE\"). /* AutoGenerated - consult createCoin.sh*/" >> houseBuilding/src/agt/inc/common.asl
cat houseBuilding/src/agt/inc/common.asl.bkp | grep -v "AutoGenerated" >> houseBuilding/src/agt/inc/common.asl
rm houseBuilding/src/agt/inc/common.asl.bkp

echo " "
echo "Updating beliefs about Giacomo Wallet"
mv houseBuilding/src/agt/giacomo.asl houseBuilding/src/agt/giacomo.asl.bkp
GiacomoPrivateKey=`cat .jacamoCoin/giacomoWallet.privkey`
GiacomoPublickKey=`cat .jacamoCoin/giacomoWallet.publkey`
echo "myWallet(\"$GiacomoPrivateKey\",\"$GiacomoPublickKey\"). /* Auto generated GiacomoWallet - consult createCoin.sh*/" > houseBuilding/src/agt/giacomo.asl
cat houseBuilding/src/agt/giacomo.asl.bkp | grep -v "Auto generated GiacomoWallet" >> houseBuilding/src/agt/giacomo.asl
rm houseBuilding/src/agt/giacomo.asl.bkp